sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
      - name: reviews
        identifier: raw_reviews
      - name: hosts
        identifier: raw_hosts